@Vestrom_Api_HostAddress = http://localhost:5229

GET {{Vestrom_Api_HostAddress}}/api/public/status
Accept: application/json

###

GET {{Vestrom_Api_HostAddress}}/api/public/health
Accept: application/json
